var gigs = '[{'
+ '"gigs": [\n'
    + '{\n'
      + '"date": "Saturday, September 1, 2018",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "Pan\'s Rambles",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/san_francisco/\\" target=\\"_blank\\">San Francisco, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Saturday, September 8, 2018",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "Pan\'s Rambles",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/palo_alto/\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, September 16, 2018",\n'
      + '"who": "Jess and Mark",\n'
      + '"band": "Pan\'s Rambles",\n'
      + '"location": "<a href=\\"https://www.bacds.org/series/contra/san_jose/\\" target=\\"_blank\\">San Jose, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Sunday, September 22, 2018",\n'
      + '"who": "Jess",\n'
      + '"band": "Jess and Derry",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/palo_alto/\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Monday, December 31, 2018",\n'
      + '"who": "Jess",\n'
      + '"band": "<a href=\\"https://www.facebook.com/pepperjackcontra/\\" target=\\"_blank\\">Pepperjack</a>",\n'
      + '"location": "<a href=\\"http://www.bacds.org/series/contra/palo_alto/\\" target=\\"_blank\\">Palo Alto, CA</a>",\n'
      + '"event": "NYE Contra dance"\n'
    + '},\n'
    + '{\n'
      + '"date": "Friday, January 11, 2019",\n'
      + '"who": "Jess",\n'
      + '"band": "<a href=\\"https://www.facebook.com/pepperjackcontra/\\" target=\\"_blank\\">Pepperjack</a>",\n'
      + '"location": "<a href=\\"http://www.lcfd.org/sf/circleleft.html/\\" target=\\"_blank\\">Oakland, CA</a>",\n'
      + '"event": "Contra dance"\n'
    + '}\n'
  + ']\n'
+ '}]\n'